//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/InputControls/InputMaster.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputMaster : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputMaster()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputMaster"",
    ""maps"": [
        {
            ""name"": ""Tracks"",
            ""id"": ""473d8f65-baf3-49df-8af6-21d3b954c6bb"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""fad97973-988e-44d1-882f-89f845b3a49a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Call"",
                    ""type"": ""Button"",
                    ""id"": ""39e7fd28-faff-4ac1-bef4-fc0706690406"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HangUp"",
                    ""type"": ""Button"",
                    ""id"": ""93139566-a400-478c-abb6-66f364afa48b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1de658ef-ea61-4ea9-943e-03679584889a"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""672a07e3-7d37-4c53-925e-9ca5071616d7"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""bf8d97b8-278c-4f2e-b3aa-457720d6284d"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""feb3dd22-198f-434a-a982-ada4b857a5a2"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""8f0d4c6f-2dd3-4169-b5e7-7b534d11dd44"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""aaa97ebb-c15d-4f08-a21d-67a2cefc0049"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c88a8371-669f-44c0-a4fc-6302cbf88395"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""Call"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""999b3776-e1ef-4e30-a78b-ccc0007f3706"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""HangUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Xbox Control Scheme"",
            ""bindingGroup"": ""Xbox Control Scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Tracks
        m_Tracks = asset.FindActionMap("Tracks", throwIfNotFound: true);
        m_Tracks_Movement = m_Tracks.FindAction("Movement", throwIfNotFound: true);
        m_Tracks_Call = m_Tracks.FindAction("Call", throwIfNotFound: true);
        m_Tracks_HangUp = m_Tracks.FindAction("HangUp", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Tracks
    private readonly InputActionMap m_Tracks;
    private ITracksActions m_TracksActionsCallbackInterface;
    private readonly InputAction m_Tracks_Movement;
    private readonly InputAction m_Tracks_Call;
    private readonly InputAction m_Tracks_HangUp;
    public struct TracksActions
    {
        private @InputMaster m_Wrapper;
        public TracksActions(@InputMaster wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Tracks_Movement;
        public InputAction @Call => m_Wrapper.m_Tracks_Call;
        public InputAction @HangUp => m_Wrapper.m_Tracks_HangUp;
        public InputActionMap Get() { return m_Wrapper.m_Tracks; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TracksActions set) { return set.Get(); }
        public void SetCallbacks(ITracksActions instance)
        {
            if (m_Wrapper.m_TracksActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_TracksActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_TracksActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_TracksActionsCallbackInterface.OnMovement;
                @Call.started -= m_Wrapper.m_TracksActionsCallbackInterface.OnCall;
                @Call.performed -= m_Wrapper.m_TracksActionsCallbackInterface.OnCall;
                @Call.canceled -= m_Wrapper.m_TracksActionsCallbackInterface.OnCall;
                @HangUp.started -= m_Wrapper.m_TracksActionsCallbackInterface.OnHangUp;
                @HangUp.performed -= m_Wrapper.m_TracksActionsCallbackInterface.OnHangUp;
                @HangUp.canceled -= m_Wrapper.m_TracksActionsCallbackInterface.OnHangUp;
            }
            m_Wrapper.m_TracksActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Call.started += instance.OnCall;
                @Call.performed += instance.OnCall;
                @Call.canceled += instance.OnCall;
                @HangUp.started += instance.OnHangUp;
                @HangUp.performed += instance.OnHangUp;
                @HangUp.canceled += instance.OnHangUp;
            }
        }
    }
    public TracksActions @Tracks => new TracksActions(this);
    private int m_XboxControlSchemeSchemeIndex = -1;
    public InputControlScheme XboxControlSchemeScheme
    {
        get
        {
            if (m_XboxControlSchemeSchemeIndex == -1) m_XboxControlSchemeSchemeIndex = asset.FindControlSchemeIndex("Xbox Control Scheme");
            return asset.controlSchemes[m_XboxControlSchemeSchemeIndex];
        }
    }
    public interface ITracksActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnCall(InputAction.CallbackContext context);
        void OnHangUp(InputAction.CallbackContext context);
    }
}
